name: trelby # you probably want to 'snapcraft register <name>'
base: core # the base snap is the execution environment for this snap
version: '2.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: A free, multiplatform, feature-rich screenwriting program # 79 char long summary
description: |
  Trelby is simple, fast and elegantly laid out to make screenwriting simple.
  It is highly configurable. Features multiple views, including drawt view and
  WYSIWYG mode, a name database, scene/location/character/dialogue reports,
  you can compare scripts across different versions and export to PDF,
  formatted text, HTML, RTF, Final Draft XML (.fdx) and Fountain formtas.

  Trelby is free software, developed by Osku Salerma, under the GPL License.
  Contributions are welcome.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: trelby/resources/icon256.png

parts:
  trelby:
    source: trelby
    plugin: python
    python-version: python2
    override-build: |
      snapcraftctl build
      echo "deb http://old-releases.ubuntu.com/ubuntu wily main universe" | sudo tee /etc/apt/sources.list.d/wily-copies.list
      sudo apt update
      mkdir $SNAPCRAFT_PART_INSTALL/opt
      mkdir $SNAPCRAFT_PART_INSTALL/opt/trelby
      cp -dR * $SNAPCRAFT_PART_INSTALL/opt/trelby/
    stage-packages:
    # - wx-common
    - python-lxml
    - python-wxgtk2.8
    - python-wxtools
    - wx2.8-i18n
    # python-packages:
    # - py2exe
apps:
  trelby:
    command: opt/trelby/src/trelby.py
    plugs:
      - x11
      - desktop
      - wayland
